---
- hosts: all
  user: deploy
  sudo: true
  gather_facts: true
  roles:
    - role: website
      website:
        name: mike.bloy.org
        directory: /srv/www/mike.bloy.org
        user: mikeweb
        group: webeditors
        groupusers:
          - mike
        root: /srv/www/mike.bloy.org
        hostnames:
          - mike.bloy.org
  tasks:
    - name: bundle install
      local_action: command bundle install
      sudo: false
      run_once: true

    - name: build site
      local_action: command bundle exec middleman build
      sudo: false
      run_once: true

    - name: rsync site
      copy:
        owner: mikeweb
        group: webeditors
        mode: 0664
        src: build/
        dest: /srv/www/mike.bloy.org
