#!/usr/bin/env ruby

require 'webrick'

include WEBrick


def start_webrick(config = {})
  config.update(:Port => 3000)
  server = HTTPServer.new(config)
  yield server if block_given?
  ['INT', 'TERM'].each do |signal|
    trap(signal) { server.shutdown }
  end
  server.start

end


docroot = File.expand_path(File.join(File.dirname(__FILE__), '..', 'public'))

start_webrick(:DocumentRoot => docroot)
